name: Build and Push Docker Image to GCP

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Authenticate with GCP
    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP }}" > /tmp/gcp-key.json
        # Debug: Check if the key file is correctly written
        # Uncomment the next line only for debugging purposes. Do NOT use this in production as it may expose sensitive data.
        cat /tmp/gcp-key.json

        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project core-dev-435517
        gcloud auth configure-docker us-central1-docker.pkg.dev

    # Step 4: Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/core-dev-435517/transcription-container/inference-github:latest .
        docker push us-central1-docker.pkg.dev/core-dev-435517/transcription-container/inference-github:latest
